server:
  port: 9000
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://112.217.238.122:3306/kshdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: KSH
    password: KSH

  data:
    web:
      pageable:
        default-page-size: 5

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        use_sql_comments: false
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

